### ISSUE TITLE
Question on Random Forest classifier as learner (rf_learner.py)

### ISSUE THREAD

**Issue by bengsoon** [vintasoftware/deduplication-slides#36]
Hi @fjsj, I bumped into your repo on the PyCon2020 slides and am trying to use that on my work, where I am currently using `dedupe` to perform some entity resolution for my data. If you don't mind, I would like to ask your question regarding your custom implementation of Random Forest that inherits the `RLRLearner` class from `dedupe` (rf_learner.py):

``` python
class RFLearner(RLRLearner):

    def __init__(self, data_model, *args, **kwargs):
        self.svm_classifier = _build_model()
        super().__init__(data_model, *args, **kwargs)

    def fit(self, X, y):
        y = numpy.array(y)

        # This replicates Dedupe's behavior, adapting it to sklearn:
        # if there are only non-matching examples on y,
        #     grab a random record and consider it as a match with itself
        # if there are only matching examples on y,
        #     grab a random pair and consider it as a non-match
        # Also, if both X and y are empty, do both things above.
        # This happens on active learning when there's no existing training_pairs.
        if not y.any():
            random_pair = random.choice(self.candidates)
            exact_match = (random_pair[0], random_pair[0])
            X = numpy.vstack([X, self.transform([exact_match])])
            y = numpy.concatenate([y, [1]])
        if numpy.count_nonzero(y) == len(y):
            random_pair = random.choice(self.candidates)
            X = numpy.vstack([X, self.transform([random_pair])])
            y = numpy.concatenate([y, [0]])

        self.y = y
        self.X = X
        self.svm_classifier.fit(X, y)

```

In the `fit()` method, you mentioned that it is replicating Dedupe's behavior to initialize the `X` and `y` when there non-matching or matching examples on `y`.  It makes perfect sense to me, but I am struggling to find where this is referenced to on Dedupe's codebase, could you please help me out with that? 

Thank you so much for your time! :)

**Comment by fjsj** [comment]
Hi @bengsoon! 
In Dedupe, this classifier is not implemented using scikit-learn. It uses a logistic regression classifier from a library called [rlr](https://github.com/dedupeio/rlr). The classifier code in current Dedupe version is here: https://github.com/dedupeio/dedupe/blob/69888842cb36b45f0bd67b68ecc34e954c577b3f/dedupe/labeler.py#L93

Does that answer your question?

**Comment by bengsoon** [comment]
Thanks so much for your reply @fjsj! I was actually referring to your custom learner implementation using Random Forest in your pycon 2020 deduplication slides.

 I would like to implement a different classifier on my work also (as you did for yours), replacing the off the shelf `rlr` classifier that dedupe has themselves.

**Comment by fjsj** [comment]
@bengsoon In [rf_dedupe.py](https://github.com/vintasoftware/deduplication-slides/blob/pycon-2020/rf_dedupe.py), `_build_model` is the model instance. It can be any sklearn classifier.

So as long as you change `_build_model` and use the `RFDedupe` from that same file, you'll be fine with another custom sklearn classifier.
